# Generated by Django 5.2.11 on 2026-06-15 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_role', models.CharField(choices=[('student', '学生项目'), ('teacher', '教师项目')], max_length=10, verbose_name='发布者身份')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(verbose_name='项目描述')),
                ('category', models.CharField(choices=[('teacher_research', '教师科研项目'), ('subject_competition', '学科竞赛'), ('innovation_innov', '大创项目-创新类'), ('innovation_venture', '大创项目-创业类')], max_length=24, verbose_name='类别')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审'), ('published', '已发布'), ('recruit_full', '已招满'), ('ended', '已结束'), ('offline', '已下架')], default='draft', max_length=20, verbose_name='状态')),
                ('recruit_count', models.PositiveSmallIntegerField(default=1, verbose_name='招募人数')),
                ('skill_requirements', models.JSONField(blank=True, default=list, verbose_name='技能要求')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('deadline', models.DateTimeField(verbose_name='招募截止时间')),
                ('is_visible_when_ended', models.BooleanField(default=True, verbose_name='已结束是否对他人可见')),
                ('offline_reason', models.CharField(blank=True, max_length=500, verbose_name='下架原因')),
                ('offline_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=500, verbose_name='驳回原因')),
                ('prev_status', models.CharField(blank=True, max_length=20, verbose_name='下架前状态')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='乐观锁版本')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_projects', to=settings.AUTH_USER_MODEL)),
                ('offline_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offlined_projects', to=settings.AUTH_USER_MODEL)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_projects', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_projects', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审核状态')),
                ('reject_reason', models.TextField(blank=True, verbose_name='驳回理由')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_comments', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='jgzx_platform.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectThreadComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thread_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_deleted_comments', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='jgzx_platform.projectthreadcomment', verbose_name='父评论')),
                ('project', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='thread_comments', to='jgzx_platform.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '互动评论',
                'verbose_name_plural': '互动评论',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(choices=[('student', '学生'), ('teacher', '教师')], default='student', max_length=10, verbose_name='身份标签')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='联系电话')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_banned', models.BooleanField(default=False, verbose_name='是否封禁')),
                ('ban_reason', models.TextField(blank=True, verbose_name='封禁原因')),
                ('banned_until', models.DateTimeField(blank=True, null=True, verbose_name='封禁截止时间')),
                ('project_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='ProjectCommentReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='已读时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_comment_read_states', to=settings.AUTH_USER_MODEL, verbose_name='项目发布者')),
                ('project', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='comment_read_states', to='jgzx_platform.project', verbose_name='项目')),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='read_state', to='jgzx_platform.projectthreadcomment', verbose_name='评论')),
            ],
            options={
                'verbose_name': '评论已读状态',
                'verbose_name_plural': '评论已读状态',
                'indexes': [models.Index(fields=['owner', 'is_read'], name='jgzx_platfo_owner_i_2c80b0_idx'), models.Index(fields=['owner', 'project', 'is_read'], name='jgzx_platfo_owner_i_8c4c5f_idx')],
            },
        ),
    ]
