# Generated by Django 5.2.11 on 2026-06-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jgzx_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contact_info',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='联系方式'),
        ),
    ]
