# Generated by Django 5.2.11 on 2026-02-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jgzx_platform', '0003_project_category_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='offline_reason',
            field=models.CharField(blank=True, max_length=500, verbose_name='下架原因'),
        ),
    ]
