# Generated by Django 5.2.11 on 2026-04-27 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jgzx_platform', '0004_project_reviewed_at_project_reviewed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectThreadComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thread_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_deleted_comments', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='jgzx_platform.projectthreadcomment', verbose_name='父评论')),
                ('project', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='thread_comments', to='jgzx_platform.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '互动评论',
                'verbose_name_plural': '互动评论',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCommentReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='已读时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_comment_read_states', to=settings.AUTH_USER_MODEL, verbose_name='项目发布者')),
                ('project', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='comment_read_states', to='jgzx_platform.project', verbose_name='项目')),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='read_state', to='jgzx_platform.projectthreadcomment', verbose_name='评论')),
            ],
            options={
                'verbose_name': '评论已读状态',
                'verbose_name_plural': '评论已读状态',
                'indexes': [models.Index(fields=['owner', 'is_read'], name='jgzx_platfo_owner_i_2c80b0_idx'), models.Index(fields=['owner', 'project', 'is_read'], name='jgzx_platfo_owner_i_8c4c5f_idx')],
            },
        ),
    ]
