# Generated by Django 5.2.11 on 2026-04-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jgzx_platform', '0005_project_tags_projectthreadcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='标签'),
        ),
    ]
